In [1]:
import os
import torch
import numpy as np 

In [2]:
def build_path(path):
    path_levels = path.split('/')
    cur_path = ""
    for path_seg in path_levels:
        if len(cur_path):
            cur_path = cur_path + '/' + path_seg
        else: 
            cur_path = path_seg
        
        if not os.path.exists(cur_path):
            os.mkdir(cur_path)

In [3]:
build_path('./text////get//se')

In [4]:
def get_label(data, order, offset, label_dim):
    output = []
    for i in order:
        output.append(data[i][offset:offset+label_dim])

    output = np.array(output, dtype='int')
    return output

In [5]:
data = [
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
]

order = [2, 0]
offset = 1
label_dim = 2

labels = get_label(data, order, offset, label_dim)
print(labels)
# Output: [[ 9 10]
#          [ 1  2]]


[[ 9 10]
 [ 1  2]]


In [6]:
def get_feat(data, order, meta_offset, label_dim, feature_dim):
    output = []
    meta_output = []
    offset = meta_offset + label_dim
    for i in order:
        meta_output.append(data[i][:meta_offset])
        output.append(data[i][offset:offset+feature_dim])

    output = np.array(output, dtype='float32')
    meta_output = np.array(meta_output, dtype='float32')
    return np.concatenate([output, meta_output], axis=1)

In [7]:
data = [
    [0.1, 0.2,   1,     10.0, 10.1, 10.2],   # meta(0.1, 0.2), label(1), feature(10.0, 10.1, 10.2)
    [0.3, 0.4,   0,     11.0, 11.1, 11.2],
]

order = [1, 0]
meta_offset = 2
label_dim = 1
feature_dim = 3

feat = get_feat(data, order, meta_offset, label_dim, feature_dim)
print(feat)


[[11.  11.1 11.2  0.3  0.4]
 [10.  10.1 10.2  0.1  0.2]]


In [16]:
def log_sum_exp(x, mask):  # mask is ignored
    max_x = torch.max(x, 1)[0] 
    print(max_x)                       # shape: (batch,)
    new_x = x - max_x.unsqueeze(1).expand_as(x)       # shape: same as x
    return max_x + (new_x.exp().sum(1)).log()         # shape: (batch,)

In [17]:
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, -1.0, 0.0]])
mask = torch.tensor([[1, 0, 1], [0, 1, 1]])

log_sum = log_sum_exp(x, mask)
print(log_sum)

tensor([3., 4.])
tensor([3.4076, 4.0247])


max -> values, indices

In [21]:
torch.max(x, 1)[0].unsqueeze(1).expand_as(x)

tensor([[3., 3., 3.],
        [4., 4., 4.]])

In [22]:
A = torch.tensor([[1, 2], [3, 4]])
A

tensor([[1, 2],
        [3, 4]])

In [23]:
A.unsqueeze(0).expand(3, -1, -1)

tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])