In [1]:
import os
import torch
import numpy as np 

In [2]:
a = torch.eye(3)
a

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [3]:
ts  = torch.nn.Linear(2, 3)
ts.weight

Parameter containing:
tensor([[-0.0802, -0.5349],
        [ 0.5406,  0.4454],
        [-0.4899, -0.1412]], requires_grad=True)

In [5]:
A = torch.randn(3, 2)
A

tensor([[ 0.8752, -0.5276],
        [ 0.8643, -0.5790],
        [-0.0828, -0.0206]])

In [7]:
ts.weight.T

tensor([[-0.0802,  0.5406, -0.4899],
        [-0.5349,  0.4454, -0.1412]], grad_fn=<PermuteBackward0>)

In [10]:
A @ ts.weight.T + ts.bias

tensor([[ 0.8170, -0.4137, -0.2577],
        [ 0.8454, -0.4424, -0.2451],
        [ 0.6227, -0.7058,  0.1400]], grad_fn=<AddBackward0>)

In [9]:
ts(A)

tensor([[ 0.8170, -0.4137, -0.2577],
        [ 0.8454, -0.4424, -0.2451],
        [ 0.6227, -0.7058,  0.1400]], grad_fn=<AddmmBackward0>)